### ISSUE TITLE
11.微信小程序在工作比较常用到的小demo

### ISSUE THREAD

**Issue by CruxF** [CruxF/StudyWXsmallProgram#11]
## 1、巧用三目运算
我们在开发中遇到“要么...就...”的逻辑判断，往往会用三目运算做一个简单判断输出，然而当我们没有什么开发经验的时候，遇到“要么...就(要么...就...)...”的问题就会一脸懵逼，甚至写if来做分步判断，其实完全没必要这么做，更简洁的写法如下
```js
{{isCapture==1?'队长':(isCapture==2?'队员':'未加入')}}
```
<br><br>

## 2、一个箭头指示效果
结构代码
```html
<view class='demo'>
  <i class="ani-first" decode='true'>{{'>'}}</i><i class="ani-second">{{'>'}}</i>
</view>
```

样式代码
```css
.demo {
  padding: 5rpx 20rpx;
  background-color: black;
  width: 100rpx;
}
.ani-first {
  opacity: 1;
  animation: ani-first 1s 0s linear infinite;
  color: #fdfff4;
}
.ani-second {
  opacity: 0;
  animation: ani-second 1s 0s linear infinite;
  color: #fdfff4;
}
@keyframes ani-first {
  0% {
    opacity: 1;
  }
  80% {
    opacity: 1;
  }
  100% {
    opacity: 0;
  }
}
@keyframes ani-second {
  0% {
    opacity: 0;
  }
  50% {
    opacity: 0;
  }
  60% {
    opacity: 1;
  }
  80% {
    opacity: 1;
  }
  100% {
    opacity: 0;
  }
}
```
<br><br>

## 3、音乐播放的应用：基于wepy框架，数据绑定有差异（一）
页面结构代码
```html
<view class="music {{playing?'music-active':''}}" bindtap="musicAct"></view>
```

样式代码
```css
.music {
  width: 50rpx;
  height: 50rpx;
  background-image: url("https://ossweb-img.qq.com/images/huaxia/music-btn-gray.png");
  background-size: 100% 100%;
}
.music-active {
  background-image: url("https://ossweb-img.qq.com/images/huaxia/music-btn.png");
  animation: rotation 3s linear infinite;
  background-size: 100% 100%;
}
@keyframes rotation {
  from {
    transform: rotate(0deg);
  }
  to {
    transform: rotate(360deg);
  }
}
```

脚本代码
```js
Page({

  /**
   * 页面的初始数据
   */
  data: {
    playing: false
  },
  // 播放音乐
  musicAct(){
    this.setData({
      playing: !this.data.playing
    })
    const music = wx.getBackgroundAudioManager()
    music.title = "华夏周年庆"
    music.src = 'https://ossweb-img.qq.com/images/huaxia/music.mp3'
    music.onError(()=>{
      wx.showToast({
        title: '播放加载失败',
      })
    })
    music.onEnded(()=>{
      music.title = "华夏周年庆"
      music.src = 'https://ossweb-img.qq.com/images/huaxia/music.mp3'
    })
    if(this.data.playing){
      music.play()
    } else {
      music.pause()
    }
  }
})
```

或者是更合理的脚本代码
```js
Page({

  /**
   * 页面的初始数据
   */
  data: {
    playing: false,
    music: null
  },
  // 播放音乐
  musicAct() {
    this.setData({
      playing: !this.data.playing
    })
    if(!this.data.music) {
      this.data.music = wx.getBackgroundAudioManager()
      this.data.music.title = "华夏周年庆"
      this.data.music.src = 'https://ossweb-img.qq.com/images/huaxia/music.mp3'
      this.data.music.onError(() => {
        wx.showToast({
          title: '播放加载失败',
        })
      })
      this.data.music.onEnded(() => {
        this.data.music.title = "华夏周年庆"
        this.data.music.src = 'https://ossweb-img.qq.com/images/huaxia/music.mp3'
      })
    }
    if (this.data.playing) {
      this.data.music.play()
    } else {
      this.data.music.pause()
    }
  }
})
```

全局app.json配置（requiredBackgroundModes），目的是支持后台播放
```js
{
  "pages": [
    "pages/demo/demo"
  ],
  "window": {
    "backgroundTextStyle": "light",
    "navigationBarBackgroundColor": "#fff",
    "navigationBarTitleText": "WeChat",
    "navigationBarTextStyle": "black"
  },
  "requiredBackgroundModes": ["audio"],
  "sitemapLocation": "sitemap.json"
}
```
<br><br>

## 4、视频播放的应用（一）
页面结构代码
```html
<view class="video">
  <video src="{{video}}" id="video"></video>
  <view class="controls" wx:if="{{!isVideoPlay}}">
    <view class="play">
      <view class="play-icon" bindtap="videoPlay"></view>
    </view>
  </view>
</view>
```

样式代码
```css
.video {
  width: 100%;
  height: 391rpx;
  position: relative;
}
.video video {
  width: 100%;
  height: 100%;
}
.controls {
  position: absolute;
  left: 0;
  top: 0;
  width: 100%;
  height: 100%;
  background-image: url("https://ossweb-img.qq.com/images/celebration/audio_bg_new.jpg");
  background-size: 100% 100%;
  z-index: 1000;
}
.play {
  width: 100%;
  height: 100%;
  background-color: rgba(0, 0, 0, 0.3);
  box-sizing: border-box;
  text-align: center;
}
.play-icon {
  width: 143rpx;
  height: 143rpx;
  position: absolute;
  left: 50%;
  top: 50%;
  transform: translate(-50%,-50%);
  background-image: url("https://ossweb-img.qq.com/images/b20181106/play.png");
  background-size: 100% 100%;
}
```

脚本代码
```js
Page({
  /**
   * 页面的初始数据
   */
  data: {
    video: 'https://apd-sochy.apdcdn.tc.qq.com/vcloud1022.tc.qq.com/1022_9b98f5a107e84491b50a03951ca95c2a.f0.mp4?vkey=E70F2BF8EE0EBC1F265EB2D06169C442A1222739468DCD2227AFC63B6B095B10D382F2A882F1769D6BCD88B3FA895284304DD28863E4B9BB8C1B219204F5CE6D6D18F296A82B0A775E1506DF3D2A5DBA8C0A1898CDD3AC4B&sha=0&ocid=600924937',
    isVideoPlay: false,
  },
  // 播放视频
  videoPlay(){
    let videoObj = wx.createVideoContext('video')
    this.setData({
      isVideoPlay: true
    })
    videoObj.play()
  }
})
```
<br><br>

## 5、图片轮播与预览
页面结构代码
```html
<view class="photo-swiper" bindtap="preview">
  <swiper current="{{swiperIndex}}" bindchange="swiperChange">
    <swiper-item wx:for="{{photoList}}" wx:key="index">
      <view>
        <image src="{{item}}" mode="aspectFit" />
      </view>
    </swiper-item>
  </swiper>
  <view class="swiper-button-prev" wx:if="{{swiperIndex>0}}" catchtap="swiperAction" data-id="sub"></view>
  <view class="swiper-button-next" wx:if="{{swiperIndex<photoList.length-1}}" catchtap="swiperAction" data-id="add"></view>
</view>
```

样式代码
```css
.photo-swiper {
  position: relative;
  width: 670rpx;
  height: 450rpx;
  background-image: url(https://ossweb-img.qq.com/images/celebration/stewardBox.png);
  background-size: 100% 100%;
  margin: 20rpx auto;
}
.photo-swiper swiper {
  width: 660rpx;
  height: 390rpx;
}
.photo-swiper swiper view {
  width: 100%;
  height: 100%;
  display: flex;
  justify-content: center;
  margin-top: 40rpx;
}
swiper image {
  height: 100%;
  width: 635rpx;
}
.swiper-button-prev {
  background-image: url("https://ossweb-img.qq.com/images/celebration/stewardleft.png");
  left: 4rpx;
  right: auto;
}
.swiper-button-next, .swiper-button-prev {
  position: absolute;
  top: 50%;
  width: 77rpx;
  height: 150rpx;
  margin-top: -75rpx;
  z-index: 10;
  cursor: pointer;
  background-size: 100% 100%;
  background-position: center;
  background-repeat: no-repeat;
}
.swiper-button-next {
  background-image: url("https://ossweb-img.qq.com/images/celebration/stewardright.png");
  right: 4rpx;
  left: auto;
}
```

脚本代码
```js
Page({
  /**
   * 页面的初始数据
   */
  data: {
    photoList: [
      'https://static.svip.game.qq.com/cms/file/170459_9572dfala_342e6a7067.jpg',
      'https://static.svip.game.qq.com/cms/file/170459_7974z7yyf_382e6a7067.jpg',
      'https://static.svip.game.qq.com/cms/file/170459_62790mpa3_31342e6a70.jpg'
    ],
    swiperIndex: 1,
  },
  // 图片预览
  preview(e) {
    wx.previewImage({ current: this.data.photoList[this.data.swiperIndex], urls: this.data.photoList });
    console.log(e)
  },
  // 图片轮播
  swiperChange(e) {
    this.setData({
      swiperIndex: e.detail.current
    })
  },
  // 图片左右轮播
  swiperAction(e) {
    if (e.currentTarget.dataset.id == 'add') {
      this.setData({
        swiperIndex: this.data.swiperIndex + 1
      })
    } else {
      this.setData({
        swiperIndex: this.data.swiperIndex - 1
      })
    }
  }
})
```
<br><br>

## 6、小程序支持动态更新内联样式
这是十分友好的一个特点，在开发中能够带来很多的便利，请看下面代码自行体会
```html
<block wx:for="{{imgs}}">
  <view style="background-image: url('{{item}}'); height: 300rpx; width: 200rpx"></view>
</block>
```

js脚本代码
```js
data: {
  imgs: [
    "https://p.ssl.qhimg.com/dmfd/400_300_/t0120b2f23b554b8402.jpg",
    "https://cw1.tw/CW/images/article/201712/article-5a261fb3057e6.jpg",
    "http://farisl.com/wp-content/uploads/2014/07/085626mbP.jpg"
  ]
}
```
