### ISSUE TITLE
13.兼容性：不能在animation中有切换图片的行为

### ISSUE THREAD

**Issue by CruxF** [CruxF/StudyWXsmallProgram#13]
为了让某张图片看上去有闪烁的动画效果，有时候我们可能会使用animation切换背景图来达到目的，比如：
```css
.light-click{
  position: absolute;
  overflow: hidden;
  height: 172rpx;
  width: 172rpx;
  left: 50%;
  margin-left: -70rpx;
}
.cus-btn1{
  height: 172rpx;
  width: 172rpx;
  animation: breathe 1.5s linear 0.5s infinite;
}
@keyframes breathe {
  0% {
    background-image: url('giftblack.png');
  }
  100% {
    background-image: url('giftlight.png');
  }
}
```

这样做会留有坑，尤其是在IOS中，会出现背景图不显示的问题，我们应该这么来写代码
```css
.light-click{
  position: absolute;
  overflow: hidden;
  height: 172rpx;
  width: 172rpx;
  left: 50%;
  margin-left: -70rpx;
  z-index: 2200;
  background-image: url("giftlight.png");
}
.cus-btn1{
  height: 172rpx;
  width: 172rpx;
  opacity: 0.3;
  background-image: url("giftlight.png");
  animation: breathe 1.5s linear 0.5s infinite;
}

@keyframes breathe {
  0% {
    opacity:0;
  }
  50% {
    opacity:1;
  }
  100% {
    opacity:0;
  }
}
```
