### ISSUE TITLE
3.scroll-view左右横向滑动效果实现

### ISSUE THREAD

**Issue by CruxF** [CruxF/StudyWXsmallProgram#3]
## 开发要点
- 1.scroll-view 中的需要滑动的元素不可以用 float 浮动；
- 2.scroll-view 中的包裹需要滑动的元素的大盒子用 display:flex; 是没有作用的；
- 3.scroll-view 中的需要滑动的元素要用 dislay:inline-block; 进行元素的横向编排；
- 4.包裹 scroll-view 的大盒子有明确的宽和加上样式-->  overflow:hidden;white-space:nowrap;

## 源代码
```html
<view class="scroll_box">
  <scroll-view class="scroll-view_x" scroll-x style="width: auto;overflow:hidden;">
    <view class="item_list">
      <view class="item_book_text">测试数据</view>
    </view>
    <view class="item_list">
      <view class="item_book_text">测试数据</view>
    </view>
    <view class="item_list">
      <view class="item_book_text">测试数据</view>
    </view>
    <view class="item_list">
      <view class="item_book_text">测试数据</view>
    </view>
    <view class="item_list">
      <view class="item_book_text">测试数据</view>
    </view>
    <view class="item_list">
      <view class="item_book_text">测试数据</view>
    </view>
  </scroll-view>
</view>
```
```css
.scroll_box {
  width: 100%;
  height: 307rpx;
  overflow: hidden;
  padding: 20rpx;
  background: #fff;
  white-space: nowrap;
}

.item_list {
  width: 160rpx;
  height: 100rpx;
  margin-right: 23rpx;
  display: inline-block;
  background-color: green;
}

```
