### ISSUE TITLE
7.微信小程序开发 scroll-view 实现锚点标记

### ISSUE THREAD

**Issue by CruxF** [CruxF/StudyWXsmallProgram#7]
[参考文章](https://blog.csdn.net/h357650113/article/details/78383175?utm_source=debugrun&utm_medium=referral)<br><br>

## 代码
wxml文件
```html
<view class='list'>
  <view bindtap='jumpTo' data-opt="list0">list0</view>
  <view bindtap='jumpTo' data-opt="list11">list11</view>
  <view bindtap='jumpTo' data-opt="list29">list29</view>
</view>
<scroll-view 
  scroll-into-view="{{toView}}" 
  scroll-y="true" 
  scroll-with-animation="true" 
  class="scr">
    <view 
      wx:for="{{list}}" 
      id="{{item}}" 
      wx:key="*this" 
      data-rol="{{item}}" 
      class="test">
      {{item}}
    </view>
</scroll-view>
```

wxss文件
```css
page {
  height: 100%;
}
.scr {
  position: relative;
  height: 100%;
}
.test {
  height: 80rpx;
}
.list {
  position: fixed;
  z-index: 9;
  top: 30rpx;
  right: 10rpx;
}
```

js文件
```js
Page({
  data: {
    list: ["list0", "list1", "list2", "list3",  "list4",  "list5",  "list6",  "list7",  "list8",  "list9",  "list10",  "list11",  "list12",  "list13",  "list14",  "list15",  "list16",  "list17",  "list18",  "list19",  "list20",  "list21",  "list22",  "list23",  "list24",  "list25",  "list26",  "list27",  "list28",  "list29"],
    toView:   'eeede'
  },

  onLoad: function() {

  },
  jumpTo: function (e) {
    // 获取标签元素上自定义的 data-opt 属性的值
    let target = e.currentTarget.dataset.opt;
    this.setData({
      toView: target
    })
  },
  onShareAppMessage: function() {

  }
})
```
