### ISSUE TITLE
9.微信小程序之swiper组件

### ISSUE THREAD

**Issue by CruxF** [CruxF/StudyWXsmallProgram#9]
## 前言
看下面代码之前建议先到[官网](https://developers.weixin.qq.com/miniprogram/dev/component/swiper.html)瞧一瞧看一看，然后再看下面的一个小demo

wxml文件
```html
<view class="nofoot-cont has-bg" wx:if="{{isNone}}">
  <view class="mainFrame">
    <swiper class="container" indicator-dots="{{indicatorDots}}" indicator-dots="{{indicatordots}}" autoplay="{{autoplay}}" interval="{{interval}}" duration="{{duration}}" circular="{{circular}}" bindchange="bindChange">
      <block wx:for="{{project_data}}" wx:key="index">
        <swiper-item class="vol-swiper-item" bindtap="onItemClick">
          <view class="vol-card" data-id="{{item.id}}" catchtap="onPostTap">
            <view class='card-header'>
              <image src='../../../images/tip1.png' class='tip-image'></image>
              <view class='user-image'>
                <image src='../../../images/product.png'></image>
                <text class='pro-item-tt'>流浪地球</text>
              </view>
              <image src='../../../images/pro_2.png' class='tip-image' bindtap='aJump' data-url='../../member/createPro/createPro'></image>
            </view>
            <view class='card-body'>
              <view class='body-box'>
                <view class="item-oper">
                  <image src='../../../images/p1.png'></image>
                  <text>报名的大赛</text>
                </view>
                <view class="item-oper">
                  <image src='../../../images/p2.png'></image>
                  <text>投递的BP</text>
                </view>
              </view>
              <view class='body-box'>
                <view class="item-oper">
                  <image src='../../../images/p3.png'></image>
                  <text>融资信息</text>
                </view>
                <view class="item-oper">
                  <image src='../../../images/p4.png'></image>
                  <text>项目计划书</text>
                </view>
              </view>
            </view>
            <view class='card-footer'>
              <view class="pro-btn">
                <text>您的项目计划书没上传，您可以</text>
                <text>1.打开电脑并在浏览器输入www.chuangcheng.org.cn/file</text>
                <text>2.在打开的网页中输入您的手机号码&密钥：{{item.key}}</text>
              </view>
              <view class="pro-tip">
                <text>更多功能，请用电脑登录</text>
                <text>创成汇官网：https://www.chuangcheng.org.cn</text>
              </view>
            </view>
          </view>
        </swiper-item>
      </block>
    </swiper>
  </view>
</view>
```

wxss文件
```css
.head-right {
  text-align: right;
  padding-right: 15rpx;
}

.head-right image {
  width: 40rpx;
  height: 40rpx;
  vertical-align: -8rpx;
}

.no-pro {
  margin-top: 200rpx;
  text-align: center;
}

.no-pro image {
  display: block;
  width: 400rpx;
  height: 400rpx;
  margin: 0 auto;
}

.no-pro text {
  display: block;
  font-size: 28rpx;
  color: #999;
  margin: 40rpx auto;
}

.no-pro a {
  display: block;
  margin: 0rpx auto;
  width: 260rpx;
  height: 80rpx;
  border: 1rpx solid #108ee9;
  line-height: 80rpx;
  color: #108ee9;
  border-radius: 40rpx;
  font-size: 28rpx;
}

.has-bg {
  background-color: #108ee9;
}

.mainFrame {
  margin-top: 0rpx;
  height: 100%;
  display: flex;
  flex-direction: column;
}

.container {
  height: 100vh;
  padding-top: 0rpx;
  background: #108ee9;
  box-sizing: border-box;
}

.vol-swiper-item {
  margin-top: 30rpx;
  box-sizing: border-box;
  padding-left: 30rpx;
  padding-right: 30rpx;
}

.vol-card {
  padding: 30rpx;
  border: 2rpx solid #ebebeb;
  border-radius: 10rpx;
  width: 75vw;
  background: #fff;
  margin: 0 auto;
}

.card-header {
  display: flex;
  flex-direction: row;
  justify-content: space-between;
}

.tip-image {
  display: inline-block;
  height: 80rpx;
  width: 80rpx;
  border-radius: 50%;
}

.user-image {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
}

.user-image .pro-item-tt {
  margin-top: 8rpx;
  font-size: 4vw;
}

.user-image image {
  width: 120rpx;
  height: 120rpx;
  border-radius: 50%;
}

.card-body {
  margin-top: 40rpx;
  display: flex;
  justify-content: center;
  flex-direction: column;
  align-items: center;
}

.body-box {
  display: flex;
  flex-direction: row;
  justify-content: space-between;
  align-items: center;
  margin-top: 10rpx;
  width: 60vw;
}

.item-oper {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  box-shadow: #ddd 0 0 10px;
  padding: 20rpx;
  width: 20vw;
}

.item-oper image {
  width: 60rpx;
  height: 60rpx;
  margin-bottom: 27rpx;
}

.card-footer {
  margin-top: 30rpx;
}

.pro-btn {
  font-size: 24rpx;
  word-break: break-all;
  line-height: 35rpx;
}

.pro-btn text {
  display: block;
}

.pro-tip {
  font-size: 24rpx;
  margin: 30rpx auto 20rpx;
  text-align: center;
}

.pro-tip text {
  line-height: 40rpx;
}

.pro-tip text:last-child {
  color: #108ee9;
}
```

js文件
```js
Page({

  /**
   * 页面的初始数据
   */
  data: {
    indicatorDots: false,
    autoplay: false,
    interval: 2000,
    indicatordots: false,
    duration: 1000,
    circular: true,
    isNone: true,
    project_data: [{
      click: 0,
      company_created_time: "2018-02-27",
      field: "高端",
      id: 6417,
      is_plan: true,
      key: "819476",
      logo: "/storage/image/190327/MuHJBpkohsHonz0ew6b2UJFhdSLsz6mDANJtafBW.jpeg",
      product_file_id: "172494",
      product_step: 1,
      state: 2,
      title: "流浪地球",
      user_id: 21491,
      view_num: 0,
      vote_num: 0,
    }, {
      click: 0,
      company_created_time: "2018-02-27",
      field: "高端",
      id: 6417,
      is_plan: true,
      key: "819476",
      logo: "/storage/image/190327/MuHJBpkohsHonz0ew6b2UJFhdSLsz6mDANJtafBW.jpeg",
      product_file_id: "172494",
      product_step: 1,
      state: 2,
      title: "流浪火星",
      user_id: 21491,
      view_num: 0,
      vote_num: 0,
    }]
  },

  /**
   * 生命周期函数--监听页面加载
   */
  onLoad: function(options) {

  },
  // swiper滑动事件
  bindChange(e){
    console.log(e)
  },
  /**
   * 生命周期函数--监听页面初次渲染完成
   */
  onReady: function() {

  },
  onPostTap: function(event) {
    var postId = event.currentTarget.dataset.id;
    console.log(postId)
  },
  /**
   * 生命周期函数--监听页面显示
   */
  onShow: function() {

  },

  /**
   * 生命周期函数--监听页面隐藏
   */
  onHide: function() {

  },

  /**
   * 生命周期函数--监听页面卸载
   */
  onUnload: function() {

  },

  /**
   * 页面相关事件处理函数--监听用户下拉动作
   */
  onPullDownRefresh: function() {

  },

  /**
   * 页面上拉触底事件的处理函数
   */
  onReachBottom: function() {

  },

  /**
   * 用户点击右上角分享
   */
  onShareAppMessage: function() {

  }
})
```
